### ISSUE TITLE
the problem in part 3 main.cpp

### ISSUE THREAD

**Issue by Hopesarr** [KeyAuth/P2C-Example#1]
so in smap at main.cpp theres a problem that doesnt makes injects this is the code in this repositorie https://prnt.sc/10pm0xd but this doesnt works instead of that making like this would work perfectly https://prnt.sc/10pm1j3

**Comment by makfncom** [comment]
Thanks. Pirate sent me your fix code and I changed it in the repository. Appreciate it.
